"""empty message

Revision ID: 0421da7ebd40
Revises: 8dee9cf667f5
Create Date: 2025-12-09 14:48:52.116516

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0421da7ebd40'
down_revision = '8dee9cf667f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('segment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dataset_id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('segment', schema=None) as batch_op:
        batch_op.create_index('idx_segment_dataset_id', ['dataset_id'], unique=False)
        batch_op.create_index('idx_segment_document_id', ['document_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('segment', schema=None) as batch_op:
        batch_op.drop_index('idx_segment_document_id')
        batch_op.drop_index('idx_segment_dataset_id')

    op.drop_table('segment')
    # ### end Alembic commands ###
